#!/bin/sh
uci set network.lan.ipaddr=192.168.100.1
uci commit network

uci set luci.main.lang='zh_cn'
uci commit luci

uci set system.@system[0].hostname='MyAprsBox'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci commit system

# disable dhcp-v6
#uci delete dhcp.lan.dhcpv6
#uci delete dhcp.lan.ra_management
#uci delete dhcp.lan.ra
#uci commit dhcp.lan

# add luci-app-command of tail tinyaprs log
uci set luci.@command[0]=command
uci set luci.@command[0].name='tinyaprs log'
uci set luci.@command[0].command='tail -n 50 /var/log/tinyaprs.log'
uci commit luci

exit 0
