#!/bin/sh
uci set network.lan.ipaddr=192.168.98.1
uci commit network

uci set luci.main.lang='zh_cn'
uci commit luci

uci set system.@system[0].hostname='MyAprsBox'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci commit system
exit 0
